spring:
  profiles:
    active: dev

app:
  paper:
    apiKey: YOUR_API_KEY
    apiSecret: YOUR_API_SECRET
    # comma‐separated list of instrument tokens to subscribe for paper trading
    instruments: []

    # if WS disconnects, retry after this many ms
    websocket:
      reconnectIntervalMs: 5000
