spring:
  profiles:
    active: dev

server:
  port: 8084
  servlet:
    context-path: /paper-service

logging:
  level:
    root: INFO
    com.algo.trading.paper: DEBUG

app:
  paper:
    instruments:
      - 738561
      - 56323
