auth:
  baseUrl: http://localhost:8081/auth-service
backtest:
  baseUrl: http://localhost:8082/backtest-service
ml:
  baseUrl: http://localhost:8083/ml-service
paper:
  baseUrl: http://localhost:8084/paper-service
live:
  baseUrl: http://localhost:8085/live-service
