spring:
  datasource:
    url: jdbc:h2:mem:gui;MODE=PostgreSQL
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: none

logging:
  level:
    root: INFO
    com.algo.trading.gui: DEBUG

services:
  auth:
    baseUrl: http://localhost:8081/auth-service
  market:
    baseUrl: http://localhost:8082/market-data-service
  ml:
    baseUrl: http://localhost:8083/ml-service
  backtest:
    baseUrl: http://localhost:8084/backtest-service
  paper:
    baseUrl: http://localhost:8085/paper-service
  live:
    baseUrl: http://localhost:8086/live-service
