logging:
  level:
    root: INFO
    com.algo.trading.gui: DEBUG

services:
  auth:
    baseUrl: http://localhost:8081/auth-service
  market:
    baseUrl: http://localhost:8082/market-service
  ml:
    baseUrl: http://localhost:8083/ml-service
  backtest:
    baseUrl: http://localhost:8084/backtest-service
  paper:
    baseUrl: http://localhost:8085/paper-service
  live:
    baseUrl: http://localhost:8086/live-service
