server:
  port: 8081
  servlet:
    context-path: /auth-service

logging:
  level:
    root: INFO
    com.algo.trading.auth: DEBUG

app:
  auth:
    apiKey: bhvduzgqkyhxfo7i
    apiSecret: lluyk94y6u505cfpae2hp7nrj3cf2m69
