server:
  port: 8081
  servlet:
    context-path: /auth-service

logging:
  level:
    root: INFO
    com.algo.trading.auth: DEBUG

app:
  auth:
    userName: <YOUR_ZERODHA_USERNAME>
    apiKey: <YOUR_API_KEY>
    apiSecret: <YOUR_API_SECRET>
    redirectUri: http://localhost:8081/auth-service/auth/session
