spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://localhost:3306/algotrading
    username: algo_user
    password: algopass
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false

server:
  port: 8082
  servlet:
    context-path: /backtest-service

logging:
  level:
    root: INFO
    com.algo.trading.backtest: DEBUG

app:
  backtest:
    lookbackDays: 365
    reportPath: reports
